#' Information about gear carrying time on entangled right whales
#' 
#' A dataset generated by Amy Knowlton of the New England Aquarium
#' as part of the PCAD/PCOD project looking at health and the impacts
#' of disturbance on vital rates in North Atlantic right whales. These
#' data are used to establish the "windows" when animals are entangled
#' and in turn to intersect those windows with estimates of health.
#' 
#' @format a data frame containing 102 rows and 9 variables:
#' \describe{
#'  \item{EGNo}{4 number code that identifies individual right whales}
#'  \item{EventNo}{Integer labelling the consecutive number of each entanglement event}
#'  \item{Date prior w/no gear}{A character variable describing the first date the 
#'  animal was seen without gear}
#'  \item{First date w/gear}{A character variable describing the first date the 
#'  animal was seen with gear}
#'  \item{Last date w/gear}{A character variable describing the last date the 
#'  animal was seen with gear}
#'  \item{line gone}{A character variable describing the first date the animal was
#'  seen that the gear is verified to be gone from the animal}
#'  \item{min time carrying gear}{Integer denoting the minimum number of days the animal was carrying the gear}
#'  \item{max dur}{Integer denoting the maximum number of days the animal was carrying the gear}
#'  \item{AmyEdits}{Comments from Amy Knowlton about individual entries she updated and/or inserted}
#' }
"etime"

#' Information about estimated start data of entanglement events
#' 
#' A dataset generated by Amy Knowlton of the New England Aquarium
#' as part of the PCAD/PCOD project looking at health and the impacts
#' of disturbance on vital rates in North Atlantic right whales. These
#' data are used to establish the start of "windows" that denote when animals 
#' are entangled and in turn to intersect those windows with estimates of health.
#' 
#' @format a data frame containing 130 rows and 6 variables:
#' \describe{
#'  \item{EntanglementId}{A unique identifier for the entanglement event in the NEAq DIGITS database}
#'  \item{EGNo}{4 number code that identifies individual right whales}
#'  \item{EventNo}{Integer labelling the consecutive number of each entanglement event}
#'  \item{StartDate}{A character variable describing the estimated first date of the 
#'  entanglement event}
#'  \item{EndDate}{A character variable describing the observed last date of the 
#'  entanglement event}
#'  \item{EntanglementComment}{Comments from Amy Knowlton about the entanglement events}
#' }
"estStartDates"