#' Prepare the individual line data for slope health plot
#'
#' This function starts with the health data generated by the model
#' takes the entanglement event window, and using these to create
#' a data object summarising the change from start to finish of
#' an entanglement window. The input values of health are: 
#' \code{healthmean} and \code{anom}, which are the estimated
#' health of each animal, and the anomaly of each animal's health
#' compared to the population median
#' 
#' @return \code{dfout} A data frame containing the health and health anomaly 
#' for each entanglement event at each of the three locations
#' @example prepSlopeHealthData()
prepSlopeHealthData <- function(){
  
  pvec <- tangleOut[, 'EndDate'] - tangleOut[, 'StartDate'] <= 365
  tangleOut <- tangleOut[pvec, ]
  dfout <- numeric(0)
  
  for(i in 1:nrow(tangleOut)){
    
    ind <- tangleOut$EGNo[i]
    tsub <- tangleOut[i, ]
    htest <- healthmean[which(ID == ind),]
    atest <- anom[which(ID == ind),]
    
    s <- match(tsub[, 'smonyr'], myName)  
    e <- match(tsub[, 'ewindmonyr'], myName)
    r <- match(tsub[, 'rec12monyr'], myName)
    gstat <- tsub[, 'gearInj']
    sVal <- htest[s]
    eVal <- htest[e]
    rVal <- htest[r]
    asVal <- atest[s]
    aeVal <- atest[e]
    arVal <- atest[r]
    
    dfi <- data.frame(egno = ind, startHealth = sVal, endHealth = eVal, recHealth = rVal, 
                      startAnom = asVal, endAnom = aeVal, recAnom = arVal, gearInjury = gstat) 
    dfout <- rbind(dfout, dfi)
  }
  
  labels <- data.frame(gearInjury = 1:6, 
                       fullLab = c('Severe Gear', 'Moderate Gear', 'Severe No Gear', 
                                   'Minor Gear', 'Moderate No Gear', 'Minor No Gear'),
                       sevLab = c('Severe', 'Moderate', 'Severe', 
                                  'Minor', 'Moderate', 'Minor'),
                       gearLab = c('Gear', 'Gear', 'No Gear', 
                                   'Gear', 'No Gear', 'No Gear'))
  
  labels$gearLab <- factor(labels$gearLab, levels = c('No Gear', 'Gear'))
  
  dfout <- tbl_df(merge(dfout, labels, by.x = 'gearInj', by.y = 'gearInjury'))
  dfout

  dfn <- dfout %>% 
    group_by(gearInj) %>% 
    summarise(n = n_distinct(egno))

  # Prepping data for horizontal Bar plot  
  dfAsum <- dfout %>% 
    group_by(gearInj) %>% 
    summarise(sAnom = median(startAnom, na.rm = TRUE), 
              endAnom = median(endAnom), 
              recAnom = median(recAnom),
              fullLab = unique(fullLab),
              sevLab = unique(sevLab),
              gearLab = unique(gearLab))
dfAsuml <- reshape2::melt(dfAsum, id.vars = c('gearInj', 'fullLab', 'sevLab', 'gearLab'))
dfAsuml$x <- rep(0:2, each = 6)

  dfAsuml <- dfAsum %>% 
    group_by(fullLab, sevLab, gearLab) %>% 
    summarise(diff1 = endAnom - sAnom,
              diff2 = recAnom - endAnom) %>% 
    reshape2::melt(id.vars = c('fullLab', 'sevLab', 'gearLab'))
  
}
